# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateApp', '0002_userdata_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='password',
            new_name='password_hash',
        ),
        migrations.AddField(
            model_name='userdata',
            name='password_salt',
            field=models.CharField(default='n', max_length=100),
        ),
    ]
