# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateApp', '0003_auto_20171011_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='password_salt',
            field=models.CharField(max_length=100),
        ),
    ]
