# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RateApp', '0004_auto_20171011_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='last_login',
            field=models.DateField(null=True),
        ),
    ]
